require:
  - rubocop-rails

AllCops:
  Exclude:
    - "db/schema.rb"
    - "vendor/**/*"
  TargetRubyVersion: 3.1


# Custom values
Style/Documentation:
  Enabled: false



# Work
Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Max: 120

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Naming/RescuedExceptionsVariableName:
  # if enabled, the default is to encourage yout o use the variable name 'e',
  # but then it warns that the variable name is not descriptive enough under 'UncommunicativeVariableName'
  Enabled: false

Rails/HelperInstanceVariable:
  # if you use references to several of these in helpers, this can be disabled
  Enabled: true

# There are a bunch of RSpec cops that can be put here, but I'm leaving them out until rspec is used

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/SymbolArray:
  Enabled: false
